// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubmerchantAPI.Models;

namespace SubmerchantAPI.Migrations
{
    [DbContext(typeof(SubmerchantDBContext))]
    [Migration("20210522090905_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubmerchantAPI.Models.PrimaryContact", b =>
                {
                    b.Property<string>("PrimaryContactID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BusinessStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeTelephone")
                        .HasColumnType("int");

                    b.Property<string>("LegalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileTelephone")
                        .HasColumnType("int");

                    b.Property<int>("NationalInsuranceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PercentageShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfBusiness")
                        .HasColumnType("int");

                    b.HasKey("PrimaryContactID");

                    b.ToTable("PrimaryContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
